<template>
  <div>
    <b-alert show variant="primary">
      <h4 class="alert-heading">Perfil Profesional</h4>
      <p>
        {{ perfil.person.summaryOfBio}}
      </p>
      <hr />
      <p class="mb-0">
        Whenever you need to, be sure to use margin utilities to keep things
        nice and tidy.
      </p>
    </b-alert>
  </div>
</template>

<script>
export default {
  data() {
    return {
      perfil: {
        person: {
          professionalHeadline: "Frontend Web Developer",
          completion: 0.75,
          showPhone: false,
          created: "2021-11-03T01:06:24Z",
          verified: true,
          flags: {
            benefits: false,
            canary: false,
            enlauSource: false,
            fake: false,
            featureDiscovery: true,
            firstSignalSent: false,
            signalsOnboardingCompleted: false,
            importingLinkedin: false,
            onBoarded: true,
            remoter: true,
            signalsFeatureDiscovery: true,
            importingLinkedinRecommendations: false,
            contactsImported: false,
            appContactsImported: false,
            genomeCompletionAcknowledged: true,
            cvImported: true,
            communityCreatedPrivate: false,
            communityCreatedClaimed: false,
            connectBenefitsViewed: true,
          },
          weight: 0,
          ggId: "1210524",
          completionStage: { stage: 3, progress: 0.2 },
          locale: "es",
          subjectId: 1210524,
          picture:
            "https://res.cloudinary.com/torre-technologies-co/image/upload/v1636986636/origin/starrgate/users/profile_2a03c0dc61eeb83934ec3e00a8affe8d30ce84da.jpg",
          hasEmail: true,
          isTest: false,
          name: "Felipe Castro Olivera",
          links: [
            {
              id: "JyQGA7bM",
              name: "linkedin",
              address:
                "https://www.linkedin.com/in/felipe-castro-olivera-2a4a08175/",
            },
          ],
          location: {
            name: "Cartagena, Bolivar, Colombia",
            shortName: "Cartagena, Bolivar, Colombia",
            country: "Colombia",
            latitude: 10.3932277,
            longitude: -75.4832311,
            timezone: "America/Bogota",
            placeId: "ChIJL_pb_8Yl9o4RaHb7oHlZMaw",
          },
          theme: "blue500",
          id: "qy0DYwly",
          pictureThumbnail:
            "https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v1636986636/origin/starrgate/users/profile_2a03c0dc61eeb83934ec3e00a8affe8d30ce84da.jpg",
          claimant: false,
          summaryOfBio:
            "Desarrollador Web Frontend con un año de experiencia en\nJavaScript, utilizando el framework Vue.js, mezclando el UI con\nCSS, Vuetify y Bootstrap. Experiencia en GIT con GitLab y GitHub.\nExperiencia en consumo de APIs, GCP, Firebase para hosting, Auth\ny Firestore. Conociendo el maravilloso mundo de MongoDB con\nAtlas y Realm.",
          weightGraph:
            "https://hcti.io/v1/image/8e8f110e-1ad8-4b3d-9de9-a91ae3e260e1",
          publicId: "felipecastroolivera",
        },
        stats: { jobs: 6, education: 2, strengths: 41 },
        strengths: [
          {
            id: "yZmXZl4j",
            code: 6080216,
            name: "Cloud services",
            proficiency: "novice",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-24T01:35:00",
          },
          {
            id: "N8JKq9ej",
            code: 6079345,
            name: "Agile methodologies",
            proficiency: "no-experience-interested",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-24T01:34:57",
          },
          {
            id: "yX7J9oxj",
            code: 76010,
            name: "GCP",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-24T01:34:54",
          },
          {
            id: "MgE7WJ7y",
            code: 56891,
            name: "Web Development",
            proficiency: "expert",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-24T01:34:50",
          },
          {
            id: "j6dOkvAN",
            code: 6083532,
            name: "MySQL database",
            proficiency: "novice",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-23T23:05:59",
          },
          {
            id: "M7GxEDzM",
            code: 226551,
            name: "API REST",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-23T23:05:38",
          },
          {
            id: "yYogY0gM",
            code: 55675,
            name: "UI design",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-23T23:05:30",
          },
          {
            id: "MvrzbJxM",
            code: 18318,
            name: "HTML5",
            proficiency: "expert",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-18T03:46:01",
          },
          {
            id: "NPG7Rw2y",
            code: 32043,
            name: "Kotlin",
            proficiency: "no-experience-interested",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:42",
          },
          {
            id: "yX7vg1Zj",
            code: 23822,
            name: "SASS",
            proficiency: "no-experience-interested",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-15T17:59:09",
          },
          {
            id: "MWwneg1M",
            code: 32059,
            name: "Scala",
            proficiency: "no-experience-interested",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:38",
          },
          {
            id: "MgEa4VEy",
            code: 28888,
            name: "REST",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-15T17:59:07",
          },
          {
            id: "yJeoKD2j",
            code: 14985,
            name: "AJAX",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-15T17:59:01",
          },
          {
            id: "MvrZ5pxM",
            code: 55521,
            name: "Front-end development",
            proficiency: "expert",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-15T17:58:56",
          },
          {
            id: "NVYAKeqy",
            code: 23813,
            name: "Node.js",
            proficiency: "novice",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-13T15:10:27",
          },
          {
            id: "ynrEV6Ly",
            code: 603224,
            name: "JavasScript",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-13T15:10:21",
          },
          {
            id: "MLz2QKPy",
            code: 9486,
            name: "GIT",
            proficiency: "expert",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-09T13:14:31",
          },
          {
            id: "j6dPeLxN",
            code: 55516,
            name: "Front end development",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-09T13:14:24",
          },
          {
            id: "M2V9r4lM",
            code: 186709,
            name: "Autodidacta",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-09T13:14:18",
          },
          {
            id: "M4n9323y",
            code: 55664,
            name: "Trabajo en equipo",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-09T13:14:16",
          },
          {
            id: "MEep0W4M",
            code: 187217,
            name: "Buena comunicación",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-09T13:14:14",
          },
          {
            id: "jwgWAeej",
            code: 55381,
            name: "Developer",
            proficiency: "proficient",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-09T13:13:54",
          },
          {
            id: "y0zKm2qM",
            code: 61332,
            name: "Software development",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:45",
          },
          {
            id: "yYo1prgM",
            code: 194792,
            name: "Material design",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:43",
          },
          {
            id: "yDKvw9vj",
            code: 6085401,
            name: "Software architecture",
            proficiency: "no-experience-interested",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:40",
          },
          {
            id: "jA9exvvj",
            code: 56482,
            name: "Strategic Thinking",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:36",
          },
          {
            id: "Nm6qPeXM",
            code: 32590,
            name: "TypeScript",
            proficiency: "no-experience-interested",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:34",
          },
          {
            id: "N8JAn2Dj",
            code: 23826,
            name: "Vue.js",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:25",
          },
          {
            id: "yX7VdAkj",
            code: 6124164,
            name: "Full Stack development",
            proficiency: "novice",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:17:24",
          },
          {
            id: "jA9edGwj",
            code: 21290,
            name: "MongoDB",
            proficiency: "novice",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:31",
          },
          {
            id: "N8JAnlDj",
            code: 36195,
            name: "Development",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:14:34",
          },
          {
            id: "MWwndaBM",
            code: 19243,
            name: "Firebase",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:14:34",
          },
          {
            id: "yDKvd88j",
            code: 63253,
            name: "JS",
            proficiency: "expert",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:14:34",
          },
          {
            id: "M3e8rGBy",
            code: 167959,
            name: "Tecnología",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:16:42",
          },
          {
            id: "Melxq8gN",
            code: 87267,
            name: "APIS",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:30",
          },
          {
            id: "M3e8rmJy",
            code: 23792,
            name: "Bootstrap",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:29",
          },
          {
            id: "yZmzdZ4j",
            code: 18374,
            name: "GitHub",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:29",
          },
          {
            id: "ydzrvXBM",
            code: 23009,
            name: "CSS",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:28",
          },
          {
            id: "jlEvD0my",
            code: 23802,
            name: "HTML",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:28",
          },
          {
            id: "NO47daoM",
            code: 18319,
            name: "Javascript",
            proficiency: "expert",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:27",
          },
          {
            id: "MBDAdYAy",
            code: 234085,
            name: "Desarrollo de software",
            proficiency: "master",
            weight: 0,
            recommendations: 0,
            media: [],
            supra: false,
            created: "2021-11-03T01:09:25",
          },
        ],
        interests: [],
        experiences: [
          {
            id: "8yZX1b9M",
            category: "education",
            name: "Tecnólogo en Sistemas",
            organizations: [
              {
                id: 793105,
                name: "Servicio Nacional del Aprendizaje-SENA",
                publicId: "ServicioNacionalDelAprendizajeSENA",
                picture:
                  "https://res.cloudinary.com/torre-technologies-co/image/upload/v1629224897/origin/bio/organizations/ykb7d7v5frmexkiwetwc.jpg",
              },
            ],
            responsibilities: [],
            fromMonth: "April",
            fromYear: "2014",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 1,
            strengths: [],
          },
          {
            id: "eynA8zlj",
            category: "jobs",
            name: "Frontend Developer",
            organizations: [{ id: 983023, name: "Rayo", publicId: "Rayo2" }],
            responsibilities: [
              "Desarrollar aplicaciones propias de la empresa para la\noptimización de procesos masivos o comunes.",
              "Desarrollo y mantención de app web para clientes corporativos\nbajo requerimientos de estos.",
              "Mantención y desarrollo de software de bodega para proceso\nfulfillment.",
              "Desarrollo de nuevos requerimientos internos de la empresa\npara solucionar problemas on demand.",
            ],
            fromMonth: "June",
            fromYear: "2021",
            toMonth: "October",
            toYear: "2021",
            remote: false,
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 1,
            strengths: [],
          },
          {
            id: "WNVv5bKN",
            category: "jobs",
            name: "Junior Frontend Web Developer",
            organizations: [
              {
                id: 971084,
                name: "Ingeniería y Arquitectura SpA",
                publicId: "IngenierAYArquitecturaSpA",
              },
            ],
            responsibilities: [
              "Mantención de página web de la empresa y otras ramas de esta.\nDesarrollo de apps internas para la optimización de procesos y\nclientes externos, usando JavaScript y Vue.js y otros como\nFirebase y GCP",
            ],
            fromMonth: "February",
            fromYear: "2018",
            toMonth: "August",
            toYear: "2018",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 2,
            strengths: [],
          },
          {
            id: "9MBxgW2y",
            category: "education",
            name: "Ingeniería de Sistemas Sistemas",
            organizations: [
              {
                id: 742568,
                name: "Universidad del Sinú",
                publicId: "UniversidadDelSin1",
                picture:
                  "https://res.cloudinary.com/torre-technologies-co/image/upload/v1604701442/origin/bio/organizations/vq7gcgpic4dfp1poc68o.png",
              },
            ],
            responsibilities: [],
            fromMonth: "July",
            fromYear: "2016",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 2,
            strengths: [],
          },
          {
            id: "7M2gzD2j",
            category: "jobs",
            name: "Operations Key Account Manager",
            organizations: [{ id: 983023, name: "Rayo", publicId: "Rayo2" }],
            responsibilities: [],
            fromMonth: "July",
            fromYear: "2020",
            toMonth: "May",
            toYear: "2021",
            remote: false,
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 3,
            strengths: [],
          },
          {
            id: "JyQzk1nN",
            category: "jobs",
            name: "Logistics Operations Specialist",
            organizations: [{ id: 983023, name: "Rayo", publicId: "Rayo2" }],
            responsibilities: [],
            fromMonth: "August",
            fromYear: "2018",
            toMonth: "June",
            toYear: "2020",
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 4,
            strengths: [],
          },
          {
            id: "vy5zZKbN",
            category: "jobs",
            name: "Promotor Empresarial",
            organizations: [
              {
                id: 766943,
                name: "Banco de Bogotá",
                publicId: "BancoDeBgoota",
              },
            ],
            responsibilities: [],
            fromMonth: "December",
            fromYear: "2017",
            toMonth: "November",
            toYear: "2018",
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 5,
            strengths: [],
          },
          {
            id: "BMLq1Ebj",
            category: "jobs",
            name: "Técnico de sistemas",
            organizations: [
              {
                id: 630846,
                name: "Laboratorio Clinico Santa Lucia",
                publicId: "LaboratorioClinicoSantaLucia",
                picture:
                  "https://res.cloudinary.com/torre-technologies-co/image/upload/v1612383017/origin/bio/organizations/g3rxyrzrlhphifvbcaiv.jpg",
              },
            ],
            responsibilities: [],
            fromMonth: "August",
            fromYear: "2015",
            toMonth: "February",
            toYear: "2017",
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 6,
            strengths: [],
          },
        ],
        awards: [],
        jobs: [
          {
            id: "eynA8zlj",
            category: "jobs",
            name: "Frontend Developer",
            organizations: [{ id: 983023, name: "Rayo", publicId: "Rayo2" }],
            responsibilities: [
              "Desarrollar aplicaciones propias de la empresa para la\noptimización de procesos masivos o comunes.",
              "Desarrollo y mantención de app web para clientes corporativos\nbajo requerimientos de estos.",
              "Mantención y desarrollo de software de bodega para proceso\nfulfillment.",
              "Desarrollo de nuevos requerimientos internos de la empresa\npara solucionar problemas on demand.",
            ],
            fromMonth: "June",
            fromYear: "2021",
            toMonth: "October",
            toYear: "2021",
            remote: false,
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 1,
            strengths: [],
          },
          {
            id: "WNVv5bKN",
            category: "jobs",
            name: "Junior Frontend Web Developer",
            organizations: [
              {
                id: 971084,
                name: "Ingeniería y Arquitectura SpA",
                publicId: "IngenierAYArquitecturaSpA",
              },
            ],
            responsibilities: [
              "Mantención de página web de la empresa y otras ramas de esta.\nDesarrollo de apps internas para la optimización de procesos y\nclientes externos, usando JavaScript y Vue.js y otros como\nFirebase y GCP",
            ],
            fromMonth: "February",
            fromYear: "2018",
            toMonth: "August",
            toYear: "2018",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 2,
            strengths: [],
          },
          {
            id: "7M2gzD2j",
            category: "jobs",
            name: "Operations Key Account Manager",
            organizations: [{ id: 983023, name: "Rayo", publicId: "Rayo2" }],
            responsibilities: [],
            fromMonth: "July",
            fromYear: "2020",
            toMonth: "May",
            toYear: "2021",
            remote: false,
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 3,
            strengths: [],
          },
          {
            id: "JyQzk1nN",
            category: "jobs",
            name: "Logistics Operations Specialist",
            organizations: [{ id: 983023, name: "Rayo", publicId: "Rayo2" }],
            responsibilities: [],
            fromMonth: "August",
            fromYear: "2018",
            toMonth: "June",
            toYear: "2020",
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 4,
            strengths: [],
          },
          {
            id: "vy5zZKbN",
            category: "jobs",
            name: "Promotor Empresarial",
            organizations: [
              {
                id: 766943,
                name: "Banco de Bogotá",
                publicId: "BancoDeBgoota",
              },
            ],
            responsibilities: [],
            fromMonth: "December",
            fromYear: "2017",
            toMonth: "November",
            toYear: "2018",
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 5,
            strengths: [],
          },
          {
            id: "BMLq1Ebj",
            category: "jobs",
            name: "Técnico de sistemas",
            organizations: [
              {
                id: 630846,
                name: "Laboratorio Clinico Santa Lucia",
                publicId: "LaboratorioClinicoSantaLucia",
                picture:
                  "https://res.cloudinary.com/torre-technologies-co/image/upload/v1612383017/origin/bio/organizations/g3rxyrzrlhphifvbcaiv.jpg",
              },
            ],
            responsibilities: [],
            fromMonth: "August",
            fromYear: "2015",
            toMonth: "February",
            toYear: "2017",
            additionalInfo: "",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 6,
            strengths: [],
          },
        ],
        projects: [],
        publications: [],
        education: [
          {
            id: "8yZX1b9M",
            category: "education",
            name: "Tecnólogo en Sistemas",
            organizations: [
              {
                id: 793105,
                name: "Servicio Nacional del Aprendizaje-SENA",
                publicId: "ServicioNacionalDelAprendizajeSENA",
                picture:
                  "https://res.cloudinary.com/torre-technologies-co/image/upload/v1629224897/origin/bio/organizations/ykb7d7v5frmexkiwetwc.jpg",
              },
            ],
            responsibilities: [],
            fromMonth: "April",
            fromYear: "2014",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 1,
            strengths: [],
          },
          {
            id: "9MBxgW2y",
            category: "education",
            name: "Ingeniería de Sistemas Sistemas",
            organizations: [
              {
                id: 742568,
                name: "Universidad del Sinú",
                publicId: "UniversidadDelSin1",
                picture:
                  "https://res.cloudinary.com/torre-technologies-co/image/upload/v1604701442/origin/bio/organizations/vq7gcgpic4dfp1poc68o.png",
              },
            ],
            responsibilities: [],
            fromMonth: "July",
            fromYear: "2016",
            highlighted: true,
            weight: 0,
            verifications: 0,
            recommendations: 0,
            media: [],
            rank: 2,
            strengths: [],
          },
        ],
        opportunities: [
          {
            id: "jpEn460y",
            interest: "jobs",
            field: "desirable-compensation-publicly-visible",
            data: false,
          },
          {
            id: "MglnPaWj",
            interest: "gigs",
            field: "desirable-compensation-publicly-visible",
            data: false,
          },
          {
            id: "yzle1QgM",
            interest: "industries",
            field: "types",
            data: [
              { code: 11144, locale: "es", name: "Desarrollo web" },
              {
                code: 11154,
                locale: "es",
                name: "Software y servicios informáticos",
              },
              { locale: "es", name: "Tecnología" },
            ],
          },
          {
            id: "ynX903RM",
            interest: "jobs",
            field: "desirable-compensation-currency",
            data: "USD$",
          },
          {
            id: "NVJqEo0N",
            interest: "jobs",
            field: "desirable-compensation-periodicity",
            data: "yearly",
          },
          {
            id: "MBZzQqlM",
            interest: "jobs",
            field: "desirable-compensation-amount",
            data: 12000,
          },
          {
            id: "M96eOKwj",
            interest: "jobs-full-time",
            field: "private",
            data: false,
          },
          { id: "NO3ZRY0N", interest: "gigs", field: "active", data: true },
          {
            id: "jlJ5G9DN",
            interest: "gigs",
            field: "desirable-compensation-currency",
            data: "USD$",
          },
          {
            id: "yd67J8GM",
            interest: "gigs",
            field: "desirable-compensation-periodicity",
            data: "hourly",
          },
          {
            id: "yk65PB2j",
            interest: "gigs",
            field: "desirable-compensation-amount",
            data: 12000,
          },
          { id: "yZ78EG0N", interest: "gigs", field: "private", data: false },
          {
            id: "M37waOmM",
            interest: "internships",
            field: "active",
            data: false,
          },
          {
            id: "Nmg5YZXj",
            interest: "internships",
            field: "desirable-compensation-currency",
            data: "USD$",
          },
          {
            id: "Me6wgXaj",
            interest: "internships",
            field: "private",
            data: false,
          },
          { id: "jAm8QOvj", interest: "hiring", field: "active", data: false },
          {
            id: "N8GLZX8y",
            interest: "jobs-full-time",
            field: "active",
            data: true,
          },
        ],
        languages: [
          { code: "es", language: "Spanish", fluency: "fully-fluent" },
          { code: "en", language: "English", fluency: "conversational" },
        ],
      },
    };
  },
};
</script>
